#!/usr/bin/env python3
"""
Interactive setup script for messaging tool configuration.
This script helps you configure email and WhatsApp services.
"""

import os
import getpass
import sys

def print_header(title):
    """Print a formatted header."""
    print("\n" + "="*60)
    print(f"  {title}")
    print("="*60)

def print_section(title):
    """Print a section header."""
    print(f"\n📋 {title}")
    print("-" * 40)

def get_user_input(prompt, default=None, sensitive=False):
    """Get user input with optional default and sensitive handling."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    if sensitive:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt).strip()
    
    return value if value else default

def test_email_config(email_user, email_password, smtp_server, smtp_port):
    """Test email configuration."""
    try:
        import smtplib
        import ssl
        
        print("   Testing email connection...")
        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_server, int(smtp_port)) as server:
            server.starttls(context=context)
            server.login(email_user, email_password)
        print("   ✅ Email configuration test successful!")
        return True
    except Exception as e:
        print(f"   ❌ Email configuration test failed: {e}")
        return False

def create_env_file(config):
    """Create .env file with configuration."""
    env_content = "# SMS Agent Configuration\n"
    env_content += "# Generated by setup_messaging.py\n\n"
    
    # Add existing required configs
    env_content += "# Core API Keys (required)\n"
    env_content += f"OPENAI_API_KEY={config.get('openai_key', 'your_openai_key_here')}\n"
    env_content += f"GOOGLE_API_KEY={config.get('google_key', 'your_google_key_here')}\n\n"
    
    # Add email config
    if config.get('email_configured'):
        env_content += "# Email Configuration\n"
        env_content += f"EMAIL_USER={config['email_user']}\n"
        env_content += f"EMAIL_PASSWORD={config['email_password']}\n"
        env_content += f"SMTP_SERVER={config['smtp_server']}\n"
        env_content += f"SMTP_PORT={config['smtp_port']}\n\n"
    
    # Add WhatsApp config
    if config.get('whatsapp_business_configured'):
        env_content += "# WhatsApp Business API Configuration\n"
        env_content += f"WHATSAPP_API_URL={config['whatsapp_api_url']}\n"
        env_content += f"WHATSAPP_TOKEN={config['whatsapp_token']}\n"
        env_content += f"WHATSAPP_PHONE_NUMBER_ID={config['whatsapp_phone_id']}\n\n"
    
    if config.get('twilio_configured'):
        env_content += "# Twilio Configuration\n"
        env_content += f"TWILIO_ACCOUNT_SID={config['twilio_sid']}\n"
        env_content += f"TWILIO_AUTH_TOKEN={config['twilio_token']}\n"
        env_content += f"TWILIO_WHATSAPP_NUMBER={config['twilio_number']}\n\n"
    
    # Add other configs
    env_content += "# Other Configuration\n"
    env_content += "SMS_API_KEY=4b7e3d9a5c8f2a6d1e9b4c7f3a2d8e5\n"
    env_content += "AWS_REGION=us-east-1\n"
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        return True
    except Exception as e:
        print(f"Error creating .env file: {e}")
        return False

def main():
    """Main setup function."""
    print_header("SMS Agent Messaging Tool Setup")
    print("This script will help you configure email and WhatsApp messaging services.")
    print("\n⚠️  Note: This will create/update your .env file with the configuration.")
    
    if not input("\nDo you want to continue? (y/n): ").lower().startswith('y'):
        print("Setup cancelled.")
        return
    
    config = {}
    
    # Check for existing API keys
    print_section("Core API Keys")
    print("First, let's check your core API keys (required for the SMS agent):")
    
    existing_openai = os.getenv('OPENAI_API_KEY')
    existing_google = os.getenv('GOOGLE_API_KEY')
    
    if existing_openai:
        print(f"   ✅ OpenAI API key found: {existing_openai[:10]}...")
        config['openai_key'] = existing_openai
    else:
        print("   ❌ OpenAI API key not found")
        config['openai_key'] = get_user_input("Enter your OpenAI API key", sensitive=True)
    
    if existing_google:
        print(f"   ✅ Google API key found: {existing_google[:10]}...")
        config['google_key'] = existing_google
    else:
        print("   ❌ Google API key not found")
        config['google_key'] = get_user_input("Enter your Google API key", sensitive=True)
    
    # Email Configuration
    print_section("Email Configuration")
    print("Choose your email provider:")
    print("1. Gmail (for production)")
    print("2. Outlook/Hotmail (for production)")
    print("3. Mailtrap (for testing - recommended for development)")
    print("4. Other SMTP server")
    print("5. Skip email configuration")
    
    email_choice = get_user_input("Select option (1-5)", "3")
    
    if email_choice in ['1', '2', '3', '4']:
        config['email_configured'] = True
        
        if email_choice == '1':  # Gmail
            config['smtp_server'] = 'smtp.gmail.com'
            config['smtp_port'] = '587'
            print("\n📧 Gmail Setup Instructions:")
            print("1. Enable 2-factor authentication on your Gmail account")
            print("2. Generate an app password: https://myaccount.google.com/apppasswords")
            print("3. Use the app password (not your regular password)")
            
        elif email_choice == '2':  # Outlook
            config['smtp_server'] = 'smtp-mail.outlook.com'
            config['smtp_port'] = '587'
            print("\n📧 Outlook Setup Instructions:")
            print("1. Enable 2-factor authentication")
            print("2. Generate an app password in Microsoft Account Security settings")
            
        elif email_choice == '3':  # Mailtrap
            config['smtp_server'] = 'sandbox.smtp.mailtrap.io'
            config['smtp_port'] = '2525'
            print("\n📧 Mailtrap Setup Instructions:")
            print("1. Sign up at https://mailtrap.io/ (free tier available)")
            print("2. Go to Email Testing → Inboxes → Your inbox")
            print("3. Copy the SMTP credentials from the integration settings")
            print("4. Mailtrap safely captures emails without sending them to real recipients")
            
        else:  # Other
            config['smtp_server'] = get_user_input("SMTP Server", "smtp.gmail.com")
            config['smtp_port'] = get_user_input("SMTP Port", "587")
        
        config['email_user'] = get_user_input("Email address")
        config['email_password'] = get_user_input("Email password (app password)", sensitive=True)
        
        # Test email configuration
        if input("\nTest email configuration? (y/n): ").lower().startswith('y'):
            test_email_config(
                config['email_user'], 
                config['email_password'], 
                config['smtp_server'], 
                config['smtp_port']
            )
    
    # WhatsApp Configuration
    print_section("WhatsApp Configuration")
    print("Choose your WhatsApp option:")
    print("1. Twilio (easier for testing)")
    print("2. WhatsApp Business API (for production)")
    print("3. Skip WhatsApp configuration")
    
    whatsapp_choice = get_user_input("Select option (1-3)", "1")
    
    if whatsapp_choice == '1':  # Twilio
        config['twilio_configured'] = True
        print("\n📱 Twilio Setup Instructions:")
        print("1. Sign up at https://www.twilio.com/")
        print("2. Get your Account SID and Auth Token from the console")
        print("3. Join the WhatsApp sandbox by sending a message to +1 415 523 8886")
        
        config['twilio_sid'] = get_user_input("Twilio Account SID")
        config['twilio_token'] = get_user_input("Twilio Auth Token", sensitive=True)
        config['twilio_number'] = get_user_input("Twilio WhatsApp Number", "+14155238886")
        
    elif whatsapp_choice == '2':  # WhatsApp Business API
        config['whatsapp_business_configured'] = True
        print("\n📱 WhatsApp Business API Setup Instructions:")
        print("1. Create a Meta Business account")
        print("2. Set up WhatsApp Business API in Meta Developer Console")
        print("3. Get your access token and phone number ID")
        
        config['whatsapp_api_url'] = get_user_input("WhatsApp API URL", "https://graph.facebook.com/v17.0")
        config['whatsapp_token'] = get_user_input("WhatsApp Access Token", sensitive=True)
        config['whatsapp_phone_id'] = get_user_input("WhatsApp Phone Number ID")
    
    # Create .env file
    print_section("Creating Configuration File")
    if create_env_file(config):
        print("✅ Configuration saved to .env file")
    else:
        print("❌ Failed to create .env file")
        return
    
    # Final instructions
    print_header("Setup Complete!")
    print("✅ Messaging tool configuration completed!")
    print("\n📋 Next steps:")
    print("1. Test the configuration: python examples/messaging_examples.py")
    print("2. Check the documentation: docs/MESSAGING_TOOL_SETUP.md")
    print("3. Start using the messaging tool in your SMS agent")
    
    if config.get('email_configured'):
        print(f"\n📧 Email configured for: {config['email_user']}")
    
    if config.get('twilio_configured'):
        print(f"📱 WhatsApp configured via Twilio")
    elif config.get('whatsapp_business_configured'):
        print(f"📱 WhatsApp configured via Business API")
    
    print("\n🔒 Security Note:")
    print("   - Your .env file contains sensitive information")
    print("   - Never commit .env files to version control")
    print("   - Keep your API keys and passwords secure")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        sys.exit(1) 